import React from 'react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Globe } from 'lucide-react';

const languages = [
  { code: 'english', name: 'English', native: 'English' },
  { code: 'hindi', name: 'Hindi', native: 'हिंदी' },
  { code: 'marathi', name: 'Marathi', native: 'मराठी' },
  { code: 'telugu', name: 'Telugu', native: 'తెలుగు' },
  { code: 'malayalam', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'gujarati', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'punjabi', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'kannada', name: 'Kannada', native: 'ಕನ್ನಡ' }
];

export const translations = {
  english: {
    home: 'Home',
    agriMitra: 'Agri Mitra',
    cropHealth: 'Crop Health',
    soilTesting: 'Soil Testing',
    loanProducts: 'Loan Products',
    applyLoan: 'Apply for Loan',
    cropInsurance: 'Crop Insurance',
    loanCalculator: 'Loan Calculator',
    trackApplication: 'Track Application',
    customerCare: 'Customer Care',
    forum: 'Farmer Forum',
    weather: 'Weather',
    iotDevices: 'IoT Devices',
    welcome: 'Welcome to TMB AgriSmart',
    tagline: 'Your Digital Agricultural Banking Partner',
    scanCrop: 'Scan Crop',
    scanSoil: 'Scan Soil',
    applyNow: 'Apply Now',
    learnMore: 'Learn More',
    submit: 'Submit',
    upload: 'Upload',
    capture: 'Capture Photo',
    analyze: 'Analyze',
    name: 'Full Name',
    mobile: 'Mobile Number',
    email: 'Email',
    aadhaar: 'Aadhaar Number',
    loanAmount: 'Loan Amount',
    cropType: 'Crop Type',
    landArea: 'Land Area (Acres)',
    selectProduct: 'Select Loan Product',
    status: 'Status',
    applicationId: 'Application ID',
    trackNow: 'Track Now'
  },
  hindi: {
    home: 'होम',
    agriMitra: 'एग्री मित्र',
    cropHealth: 'फसल स्वास्थ्य',
    soilTesting: 'मिट्टी परीक्षण',
    loanProducts: 'ऋण उत्पाद',
    applyLoan: 'ऋण के लिए आवेदन करें',
    cropInsurance: 'फसल बीमा',
    loanCalculator: 'ऋण कैलकुलेटर',
    trackApplication: 'आवेदन ट्रैक करें',
    customerCare: 'ग्राहक सेवा',
    forum: 'किसान मंच',
    weather: 'मौसम',
    iotDevices: 'IoT उपकरण',
    welcome: 'TMB एग्रीस्मार्ट में आपका स्वागत है',
    tagline: 'आपका डिजिटल कृषि बैंकिंग साथी',
    scanCrop: 'फसल स्कैन करें',
    scanSoil: 'मिट्टी स्कैन करें',
    applyNow: 'अभी आवेदन करें',
    learnMore: 'और जानें',
    submit: 'जमा करें',
    upload: 'अपलोड करें',
    capture: 'फोटो खींचें',
    analyze: 'विश्लेषण करें',
    name: 'पूरा नाम',
    mobile: 'मोबाइल नंबर',
    email: 'ईमेल',
    aadhaar: 'आधार नंबर',
    loanAmount: 'ऋण राशि',
    cropType: 'फसल का प्रकार',
    landArea: 'भूमि क्षेत्र (एकड़)',
    selectProduct: 'ऋण उत्पाद चुनें',
    status: 'स्थिति',
    applicationId: 'आवेदन आईडी',
    trackNow: 'अभी ट्रैक करें'
  },
  marathi: {
    home: 'होम',
    agriMitra: 'एग्री मित्र',
    cropHealth: 'पीक आरोग्य',
    soilTesting: 'माती परीक्षण',
    loanProducts: 'कर्ज उत्पादने',
    applyLoan: 'कर्जासाठी अर्ज करा',
    cropInsurance: 'पीक विमा',
    loanCalculator: 'कर्ज कॅल्क्युलेटर',
    trackApplication: 'अर्ज ट्रॅक करा',
    customerCare: 'ग्राहक सेवा',
    forum: 'शेतकरी मंच',
    weather: 'हवामान',
    iotDevices: 'IoT उपकरणे',
    welcome: 'TMB एग्रीस्मार्टमध्ये आपले स्वागत आहे',
    tagline: 'तुमचा डिजिटल कृषी बँकिंग भागीदार',
    scanCrop: 'पीक स्कॅन करा',
    scanSoil: 'माती स्कॅन करा',
    applyNow: 'आता अर्ज करा',
    learnMore: 'अधिक जाणून घ्या',
    submit: 'सबमिट करा',
    upload: 'अपलोड करा',
    capture: 'फोटो काढा',
    analyze: 'विश्लेषण करा',
    name: 'पूर्ण नाव',
    mobile: 'मोबाईल नंबर',
    email: 'ईमेल',
    aadhaar: 'आधार क्रमांक',
    loanAmount: 'कर्जाची रक्कम',
    cropType: 'पिकाचा प्रकार',
    landArea: 'जमीन क्षेत्र (एकर)',
    selectProduct: 'कर्ज उत्पादन निवडा',
    status: 'स्थिती',
    applicationId: 'अर्ज आयडी',
    trackNow: 'आता ट्रॅक करा'
  },
  telugu: {
    home: 'హోమ్',
    agriMitra: 'అగ్రి మిత్ర',
    cropHealth: 'పంట ఆరోగ్యం',
    soilTesting: 'నేల పరీక్ష',
    loanProducts: 'రుణ ఉత్పత్తులు',
    applyLoan: 'రుణం కోసం దరఖాస్తు చేయండి',
    cropInsurance: 'పంట బీమా',
    loanCalculator: 'రుణ కాలిక్యులేటర్',
    trackApplication: 'దరఖాస్తు ట్రాక్ చేయండి',
    customerCare: 'కస్టమర్ కేర్',
    forum: 'రైతు ఫోరమ్',
    weather: 'వాతావరణం',
    iotDevices: 'IoT పరికరాలు',
    welcome: 'TMB అగ్రిస్మార్ట్‌కు స్వాగతం',
    tagline: 'మీ డిజిటల్ వ్యవసాయ బ్యాంకింగ్ భాగస్వామి',
    scanCrop: 'పంట స్కాన్ చేయండి',
    scanSoil: 'నేల స్కాన్ చేయండి',
    applyNow: 'ఇప్పుడు దరఖాస్తు చేయండి',
    learnMore: 'మరింత తెలుసుకోండి',
    submit: 'సమర్పించండి',
    upload: 'అప్‌లోడ్ చేయండి',
    capture: 'ఫోటో తీయండి',
    analyze: 'విశ్లేషించండి',
    name: 'పూర్తి పేరు',
    mobile: 'మొబైల్ నంబర్',
    email: 'ఇమెయిల్',
    aadhaar: 'ఆధార్ నంబర్',
    loanAmount: 'రుణ మొత్తం',
    cropType: 'పంట రకం',
    landArea: 'భూమి విస్తీర్ణం (ఎకరాలు)',
    selectProduct: 'రుణ ఉత్పత్తిని ఎంచుకోండి',
    status: 'స్థితి',
    applicationId: 'దరఖాస్తు ID',
    trackNow: 'ఇప్పుడు ట్రాక్ చేయండి'
  },
  malayalam: {
    home: 'ഹോം',
    agriMitra: 'അഗ്രി മിത്ര',
    cropHealth: 'വിള ആരോഗ്യം',
    soilTesting: 'മണ്ണ് പരിശോധന',
    loanProducts: 'ലോൺ ഉൽപ്പന്നങ്ങൾ',
    applyLoan: 'ലോണിന് അപേക്ഷിക്കുക',
    cropInsurance: 'വിള ഇൻഷുറൻസ്',
    loanCalculator: 'ലോൺ കാൽക്കുലേറ്റർ',
    trackApplication: 'അപേക്ഷ ട്രാക്ക് ചെയ്യുക',
    customerCare: 'കസ്റ്റമർ കെയർ',
    forum: 'കർഷക ഫോറം',
    weather: 'കാലാവസ്ഥ',
    iotDevices: 'IoT ഉപകരണങ്ങൾ',
    welcome: 'TMB അഗ്രിസ്മാർട്ടിലേക്ക് സ്വാഗതം',
    tagline: 'നിങ്ങളുടെ ഡിജിറ്റൽ കാർഷിക ബാങ്കിംഗ് പങ്കാളി',
    scanCrop: 'വിള സ്കാൻ ചെയ്യുക',
    scanSoil: 'മണ്ണ് സ്കാൻ ചെയ്യുക',
    applyNow: 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    learnMore: 'കൂടുതൽ അറിയുക',
    submit: 'സമർപ്പിക്കുക',
    upload: 'അപ്‌ലോഡ് ചെയ്യുക',
    capture: 'ഫോട്ടോ എടുക്കുക',
    analyze: 'വിശകലനം ചെയ്യുക',
    name: 'പൂർണ്ണ നാമം',
    mobile: 'മൊബൈൽ നമ്പർ',
    email: 'ഇമെയിൽ',
    aadhaar: 'ആധാർ നമ്പർ',
    loanAmount: 'ലോൺ തുക',
    cropType: 'വിള തരം',
    landArea: 'ഭൂമി വിസ്തീർണ്ണം (ഏക്കർ)',
    selectProduct: 'ലോൺ ഉൽപ്പന്നം തിരഞ്ഞെടുക്കുക',
    status: 'സ്ഥിതി',
    applicationId: 'അപേക്ഷ ID',
    trackNow: 'ഇപ്പോൾ ട്രാക്ക് ചെയ്യുക'
  },
  gujarati: {
    home: 'હોમ',
    agriMitra: 'એગ્રી મિત્ર',
    cropHealth: 'પાક આરોગ્ય',
    soilTesting: 'જમીન પરીક્ષણ',
    loanProducts: 'લોન ઉત્પાદનો',
    applyLoan: 'લોન માટે અરજી કરો',
    cropInsurance: 'પાક વીમો',
    loanCalculator: 'લોન કેલ્ક્યુલેટર',
    trackApplication: 'અરજી ટ્રૅક કરો',
    customerCare: 'ગ્રાહક સેવા',
    forum: 'ખેડૂત મંચ',
    weather: 'હવામાન',
    iotDevices: 'IoT ઉપકરણો',
    welcome: 'TMB એગ્રીસ્માર્ટમાં આપનું સ્વાગત છે',
    tagline: 'તમારો ડિજિટલ કૃષિ બેંકિંગ ભાગીદાર',
    scanCrop: 'પાક સ્કેન કરો',
    scanSoil: 'જમીન સ્કેન કરો',
    applyNow: 'હવે અરજી કરો',
    learnMore: 'વધુ જાણો',
    submit: 'સબમિટ કરો',
    upload: 'અપલોડ કરો',
    capture: 'ફોટો લો',
    analyze: 'વિશ્લેષણ કરો',
    name: 'પૂરું નામ',
    mobile: 'મોબાઇલ નંબર',
    email: 'ઈમેલ',
    aadhaar: 'આધાર નંબર',
    loanAmount: 'લોન રકમ',
    cropType: 'પાક પ્રકાર',
    landArea: 'જમીન વિસ્તાર (એકર)',
    selectProduct: 'લોન ઉત્પાદન પસંદ કરો',
    status: 'સ્થિતિ',
    applicationId: 'અરજી ID',
    trackNow: 'હવે ટ્રૅક કરો'
  },
  punjabi: {
    home: 'ਹੋਮ',
    agriMitra: 'ਐਗਰੀ ਮਿੱਤਰ',
    cropHealth: 'ਫਸਲ ਸਿਹਤ',
    soilTesting: 'ਮਿੱਟੀ ਟੈਸਟਿੰਗ',
    loanProducts: 'ਕਰਜ਼ਾ ਉਤਪਾਦ',
    applyLoan: 'ਕਰਜ਼ੇ ਲਈ ਅਰਜ਼ੀ ਦਿਓ',
    cropInsurance: 'ਫਸਲ ਬੀਮਾ',
    loanCalculator: 'ਕਰਜ਼ਾ ਕੈਲਕੂਲੇਟਰ',
    trackApplication: 'ਅਰਜ਼ੀ ਟ੍ਰੈਕ ਕਰੋ',
    customerCare: 'ਗਾਹਕ ਸੇਵਾ',
    forum: 'ਕਿਸਾਨ ਫੋਰਮ',
    weather: 'ਮੌਸਮ',
    iotDevices: 'IoT ਉਪਕਰਨ',
    welcome: 'TMB ਐਗਰੀਸਮਾਰਟ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    tagline: 'ਤੁਹਾਡਾ ਡਿਜੀਟਲ ਖੇਤੀਬਾੜੀ ਬੈਂਕਿੰਗ ਸਾਥੀ',
    scanCrop: 'ਫਸਲ ਸਕੈਨ ਕਰੋ',
    scanSoil: 'ਮਿੱਟੀ ਸਕੈਨ ਕਰੋ',
    applyNow: 'ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ',
    learnMore: 'ਹੋਰ ਜਾਣੋ',
    submit: 'ਜਮ੍ਹਾਂ ਕਰੋ',
    upload: 'ਅੱਪਲੋਡ ਕਰੋ',
    capture: 'ਫੋਟੋ ਖਿੱਚੋ',
    analyze: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    name: 'ਪੂਰਾ ਨਾਮ',
    mobile: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    email: 'ਈਮੇਲ',
    aadhaar: 'ਆਧਾਰ ਨੰਬਰ',
    loanAmount: 'ਕਰਜ਼ੇ ਦੀ ਰਕਮ',
    cropType: 'ਫਸਲ ਦੀ ਕਿਸਮ',
    landArea: 'ਜ਼ਮੀਨ ਖੇਤਰ (ਏਕੜ)',
    selectProduct: 'ਕਰਜ਼ਾ ਉਤਪਾਦ ਚੁਣੋ',
    status: 'ਸਥਿਤੀ',
    applicationId: 'ਅਰਜ਼ੀ ID',
    trackNow: 'ਹੁਣੇ ਟ੍ਰੈਕ ਕਰੋ'
  },
  kannada: {
    home: 'ಹೋಮ್',
    agriMitra: 'ಅಗ್ರಿ ಮಿತ್ರ',
    cropHealth: 'ಬೆಳೆ ಆರೋಗ್ಯ',
    soilTesting: 'ಮಣ್ಣು ಪರೀಕ್ಷೆ',
    loanProducts: 'ಸಾಲ ಉತ್ಪನ್ನಗಳು',
    applyLoan: 'ಸಾಲಕ್ಕೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    cropInsurance: 'ಬೆಳೆ ವಿಮೆ',
    loanCalculator: 'ಸಾಲ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    trackApplication: 'ಅರ್ಜಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    customerCare: 'ಗ್ರಾಹಕ ಸೇವೆ',
    forum: 'ರೈತ ವೇದಿಕೆ',
    weather: 'ಹವಾಮಾನ',
    iotDevices: 'IoT ಸಾಧನಗಳು',
    welcome: 'TMB ಅಗ್ರಿಸ್ಮಾರ್ಟ್‌ಗೆ ಸ್ವಾಗತ',
    tagline: 'ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಕೃಷಿ ಬ್ಯಾಂಕಿಂಗ್ ಪಾಲುದಾರ',
    scanCrop: 'ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    scanSoil: 'ಮಣ್ಣು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    applyNow: 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    learnMore: 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
    submit: 'ಸಲ್ಲಿಸಿ',
    upload: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    capture: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    analyze: 'ವಿಶ್ಲೇಷಿಸಿ',
    name: 'ಪೂರ್ಣ ಹೆಸರು',
    mobile: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    email: 'ಇಮೇಲ್',
    aadhaar: 'ಆಧಾರ್ ಸಂಖ್ಯೆ',
    loanAmount: 'ಸಾಲದ ಮೊತ್ತ',
    cropType: 'ಬೆಳೆ ಪ್ರಕಾರ',
    landArea: 'ಭೂಮಿ ವಿಸ್ತೀರ್ಣ (ಎಕರೆ)',
    selectProduct: 'ಸಾಲ ಉತ್ಪನ್ನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    status: 'ಸ್ಥಿತಿ',
    applicationId: 'ಅರ್ಜಿ ID',
    trackNow: 'ಈಗ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ'
  }
};

export default function LanguageSelector({ language, setLanguage, compact = false }) {
  return (
    <Select value={language} onValueChange={setLanguage}>
      <SelectTrigger className={compact ? "w-[100px] bg-white/10 border-white/20 text-white" : "w-[180px]"}>
        <Globe className="w-4 h-4 mr-2" />
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        {languages.map((lang) => (
          <SelectItem key={lang.code} value={lang.code}>
            {lang.native}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

export { languages };